name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: 'rustfmt, clippy'
      - uses: actions/checkout@master
      - name: Check Cargo version
        run: cargo --version
      - name: Check Rustc version
        run: rustc --version
      - name: Check format
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-features -- -D warnings
