name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        rust: [ stable, nightly ]

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: 'rustfmt, clippy'
      - uses: actions/checkout@master
      - name: Check Cargo version
        run: cargo --version
      - name: Check Rustc version
        run: rustc --version
      - name: Check format
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-features -- -D warnings
      - name: Run tests
        run: |
          cargo test --verbose --all
